<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<a href="index.php">volver</a><br>
    haz login:
    <form action="index.php?c=user" method="POST">
        <input type="text" name="username" placeholder="nombnre de usario">
        <input type="password" name="password">
        <input type="submit" name="login">
</form>
</body>
</html>