<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="index.php?c=product&add" method="POST">
        <input type="text" name="name" placeholder="nombre del producto"><br><br>
        <input type="text" name="description" placeholder="descripcion del producto"><br><br>
        <input type="number" name="price" placeholder="precio del producto"><br><br>
        <input type="number" name="stock" placeholder="stock del producto"><br><br>
        <input type="submit" value="Añadir">
</form>
</body>
</html>