<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Tienda Online</title>
    <link rel="stylesheet" href="public/style/style.css">
</head>
<body>

<div class="nav">
    <strong>🛒 Tienda Online</strong>
    <?php
    if(isset($_SESSION['user'])){
        echo "Hola <b>".$_SESSION['user']->getUsername()."</b>";
        echo " | <a href='index.php?c=product&new'>Subir producto</a>";
        echo " | <a href='index.php?logout=1' style='color: red'>Cerrar sesión</a>";
    }
    else {
        echo "<a href='index.php?login=1'>Entrar</a>";
        echo " | <a href='index.php?register=1'>Registrarse</a>";
    }
    echo " | <a href='index.php?cart=1'>Ver carrito</a>";
    ?>
</div>

<h2>Catálogo de productos</h2>

<?php
foreach($products as $product){
    ?>
    <div class="producto">
        <b><?= $product->getName() ?></b><br><br>
        <?= $product->getDescription() ?><br><br>
        Precio: <?= $product->getPrice() ?> € | Stock: <?= $product->getStock() ?><br>
        <form action="index.php?c=cart" method="POST">
            <input type="hidden" name="product_id" value="<?= $product->getId() ?>"><br>
            <input type="number" name="quantity" value="1" min="1"  style="width: 50px" max="<?= $product->getStock() ?>">
            <button type="submit" name="addcart">Añadir al carrito</button>
        </form>
    </div>
    <?php
}
?>

</body>
</html>