<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo producto</title>
</head>
<body>
<a href="index.php">volver</a><br>
    subir producto:
    <form action="index.php?c=product&add" method="POST">
        <input type="text"   name="name"        placeholder="nombre"><br>
        <input type="text"   name="description" placeholder="descripcion"><br>
        <input type="number" name="price"        placeholder="precio" step="0.01"><br>
        <input type="number" name="stock"        placeholder="stock"><br>
        <input type="submit" value="Aniadir producto">
    </form>
</body>
</html>
